kind: Deployment
apiVersion: app/v1
metadata:
  name: devops
spec: 
  replicas: 2
  selector:
    matchLables:
      app: devops
  template:
    metadata:
      labels:
        app: devops
      spec:
        containers:
          -name: devops
           image: markhor1995/jenkins-k8s-demo
           imagePullPolicy: Always
           ports:
           - containerPort: 80
  